### ISSUE TITLE
How to make this work on a Mac?

### ISSUE THREAD

**Issue by sel-carlitos** [rycus86/docker-pycharm-pro#8]
I tried to run it but I get this on my MacBook Pro:

![image](https://user-images.githubusercontent.com/35771489/84325383-a310be80-ab48-11ea-91ad-b51e5fd2aa9d.png)

**Comment by rycus86** [comment]
Hi,

On OS X, you'll need an X11 environment, have a look at https://www.xquartz.org

**Comment by sel-carlitos** [comment]
Thanks for the prompt feedback!
